<?php
$ROUTES = array(
				/*web*/
				"/home",
				"/upload",
				"/upload/video",
				"/upload/music",
				"/upload/image",
				"/help",
				"/search",
				"/search/friends",
				"/login",
				"/login/local",
				"/login/:sl",
				"/aspirationtravia/viewaspirasi/:aspiratontraviaid",
				"/aspirationtravia/viewaspirasi/:aspiratontraviaid/:start",
				"/goahead/travia/:traviaid",
				"/personalquis/view/:traviaid",
				"/story/view/:traviaid",
				"/logout",
				"/administrator/edit/:uid"
				);
?>